### ISSUE TITLE
Create keyrings programmatically for all backends that support multiple keyrings

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/keyring#105]
I.e. expose the `password` argument in `keyring_create()`.

**Comment by CristianoOliveira1** [comment]
This feature would solve my problem.. but is there any workaround for the moment? I am trying to setup a initial configuration on a docker image, and so far i have not been able to surround the problem that the R function prompts the user for a password.. Is there a way to pass it, through bash or any other way?!
Thank you in advance!
Cristiano

**Comment by gaborcsardi** [comment]
This is a duplicate of #114, and it is also solved now.
