### ISSUE TITLE
Allow definition of prompt in key_set()

### ISSUE THREAD

**Issue by pnacht** [r-lib/keyring#112]
`key_set` calls `askpass::askpass` (with many intermediate calls along the way) to display the UI. `askpass::askpass` takes a single argument `prompt` which is shown above the textbox.

The call to `askpass::askpass` is done within `get_pass`, which also takes `prompt` as an argument (default `"Password: "`). However, the call to `get_pass` (in `b_wincred_set` at least) is argument-less: `get_pass()`. Therefore the UI is effectively hard-coded to display "Password: " as the prompt.

Since the secrets stored on the keychain aren't necessarily passwords, it'd be great if that prompt were customizable.

**Comment by gaborcsardi** [comment]
Do you want to submit a PR?

**Comment by gaborcsardi** [comment]
Fixed in #113.
