### ISSUE TITLE
keyring_create does not support the 'password' argument

### ISSUE THREAD

**Issue by gongcastro** [r-lib/keyring#114]
Hi! I'm using keyring to manage passwords in a [shiny-verse](https://hub.docker.com/r/rocker/shiny) Docker image. This image lacks any existing keyring (i.e., keyring's default 'system' keyring does not exist), so I need to create it when building the image. I need to do it non-interactively: I can't write down the keyring password in a dialog box like I would to in a RStudio session.

If I understand correctly the `keyring_create` [documentation](https://github.com/r-lib/keyring/blob/167a5e044395d7d86a81299b74a273550bd5038f/R/api.R#L183-L184), this function should take the `password` argument. However, when I do so I get:
```r
keyring_create("my-keyring", password = "my-password")
# Error in keyring_create("my-keyring", password = "my-password") : 
#  unused argument (password = "my-password")
```
Is this function supposed to take a password argument? If not, is there any way to create a keyring in a non-interactive session?

Thanks!

Session info:
````
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] keyring_1.2.0

loaded via a namespace (and not attached):
[1] compiler_3.6.3   assertthat_0.2.1 R6_2.5.1         tools_3.6.3
```

**Comment by spgarbet** [comment]
This would solve #116 as well, by allowing the package user to do their own password prompting.

On a mac for every secret stored that it retrieves it asks for a password even when I'm saying "Allow All". This is terrible for my mac users that need 5-10 secrets stored per project. If I could specify the password on the call, I could just ask for it up front and control that experience a lot better.

**Comment by spgarbet** [comment]
Thank you! I'll put this through the paces today.

**Comment by gongcastro** [comment]
Thank you @gaborcsardi!
