### ISSUE TITLE
Is there a way to change the keyring password for the file backend other than deleting and re-creating the keyring ?

### ISSUE THREAD

**Issue by jbodart-argenx** [r-lib/keyring#126]
Hi, I'd like to be able to easily change the keyring password on the file backend, without having to delete it, recreate it and re-set all keys.  I couldn't find a function / method for that.  Does it already exist, or could it be implemented ?

**Comment by gaborcsardi** [comment]
Maybe there isn't a way? Right, @nbenn ?

**Comment by samuel-colin-foph** [comment]
@nbenn: if there is a way, I would be very interested as well.

**Comment by gaborcsardi** [comment]
Seems like there is no way, other than iterating over the secrets and copying them into a new keyring.
