### ISSUE TITLE
File-based password store

### ISSUE THREAD

**Issue by nbenn** [r-lib/keyring#52]
Are there plans for adding a file-based password store in addition to/instead of the env backend?

**Comment by nbenn** [comment]
Would you be interested in me having a go at this?

What do you mean by "session key"?

Are you referring to holding on to the en/decryption key for the duration of the R session? In that case, we could just have a private `key` field:

- the `keyring_is_locked()` method would return FALSE as long as the `key` field is not set
- `keyring_unlock()`ing a keyring saves the key to `private$key` and potentially tries to decrypt the file using the key
- `keyring_lock()` un-sets `private$key`

**Comment by gaborcsardi** [comment]
> Would you be interested in me having a go at this?

Yes! If you have some plans, please let me know. It does not have to be polished, of course. I think we could probably use the sodium package, that's the easiest. Or openssl is good as well.

> Are you referring to holding on to the en/decryption key for the duration of the R session? In that case, we could just have a private key field:

YEah, maybe we can just store it in the R session, that would make sense.

**Comment by nbenn** [comment]
So, I have been putting together a file-based keyring store and basic functionality is available at https://github.com/nbenn/keyring.

Some stuff is still missing like listing of items, get/setting raw secrets, etc. But before putting more time into this, I thought it might be a good idea to get some quick feedback, i.e. whether you think that in general the direction I am heading seems reasonable.

If you want me to explain some of my decisions, I'm happy to. Also I'm happy to change stuff if you don't like certain aspects.

As per your suggestion, I used sodium. I just noticed that there is some duplicated functionality between my file based backend and the wincred backend (which uses openssl). Funnily enough I independently had some similar ideas, like the `Verify` field but there are also some differences, like how I handle the session credential, so I think it would be a bit of effort (also on the wincred side) to merge common functionality.

If you like what you see so far, I'm happy to add the missing stuff to the file backend and write more tests + docs.

**Comment by gaborcsardi** [comment]
I'll take a look soon. Can you submit it as a PR, for simplicity?

**Comment by nbenn** [comment]
I just realized that there's a slight problem with what I did so far. As soon as it's fixed I will submit the PR.

**Comment by nbenn** [comment]
Sorry for the delay. Looking forward to your thoughts. Let me know if you want me to explain anything in more detail.

**Comment by gaborcsardi** [comment]
Closed  by #54.
