### ISSUE TITLE
Consider adding support for 'key_list' for 'env' backend

### ISSUE THREAD

**Issue by javierluraschi** [r-lib/keyring#57]
It would be great to support 'key_list' in 'keyring', at least for named services since this is a common configuration in RStudio Server while using `.rs.askForSecret()` in the RStudio API, will send a PR.

**Comment by gaborcsardi** [comment]
With making the 'file' backend the default fallback now, I don't think this is very important. Especially that it is actually hard/impossible to implement without changing either the env var names or their contents. Because currently any env var can be a secret as far as keyring is concerned.
