### ISSUE TITLE
Colon character not allowed in environment variables in BASH

### ISSUE THREAD

**Issue by cantpitch** [r-lib/keyring#59]
Currently, the env backend uses the colon (:) to separate the service from the user name, however this is technically invalid and makes it difficult to set that environment variable before running an R script that relies on it.

e.g.
`/# export Test:testuser=testpassword`
`bash: export: 'Test:testuser=testpassword': not a valid identifier`

I recommend using a different character string (like "__" -- two underscores).

**Comment by gaborcsardi** [comment]
You can set it from within R, e.g. via an `.Renviron` file.

**Comment by gaborcsardi** [comment]
I agree this is not ideal, but as the env backend is not that important any more, I am going to close this. You can still set the env vars in R or from `.Renviron`. But it is in general better to use the 'file' backend.
