### ISSUE TITLE
username could default to the current (system) username

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/keyring#60]
At least  in `key_get()`, maybe  also on `key_set()`.

**Comment by anssonliang** [comment]
have you solved the key_get() issue where username could default to the current system user?

**Comment by gaborcsardi** [comment]
You mean this very issue? I guess I haven't, that's why it is still open.

**Comment by anssonliang** [comment]
Yes, it bugs me when working on appbot. Obviously If the username is included in the key_get(), the error is gone. 

> keyring::key_get("appbot_api", "SNxxxxxxBG")
[1] "d8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkS"

> keyring::key_get("appbot_api")
Error in b_wincred_i_get(target) : 
  Windows credential store error in 'get': Element not found.

**Comment by gaborcsardi** [comment]
Well, this would make sense, but it is a breaking change at this point, because the username is optional for a key.

Instead, I can introduce an option, which you can set to opt in.
