### ISSUE TITLE
Keyring and Shinyapps.io

### ISSUE THREAD

**Issue by lukebunge** [r-lib/keyring#62]
Hello,

Is there a way to use keyring with an r shiny application deployed on shinyapps.io? My goal is encrypt my MySQL password in the code should anyone somehow get access to my code bundle.

Thanks in advance.

**Comment by gaborcsardi** [comment]
@lukebunge Unfortunately, there is no way to do this with keyring (or any other similar tool) currently, as shinyapps.io does not provide a credential store.

The current best practice is to put your password in an env var, set via an `.Renviron` file in the _project_ directory. The shinyapps.io deployment will pick it up from there automatically. This way at least you don't need to put in the code. You need to avoid committing the `.Renviron` file, of course.

**Comment by lukebunge** [comment]
Thanks for reponse, @gaborcsardi. I've added an .Renviron file to the project directory. That works great, however how to I avoid committing the file to the bundle?

**Comment by gaborcsardi** [comment]
It has to be deployed to shinyapps.io, of course. But you can put it in your `.gitignore` file, and then  git  will simply ignore it.

**Comment by lukebunge** [comment]
Gotcha. I placed the .Renviron file into the github repository and added a line of .Renviron file to the .gitignore file, but that still brought along the .Renviron file. What is the proper method so it doesn't commit to the shinyapps.io bundle.

**Comment by gaborcsardi** [comment]
> doesn't commit to the shinyapps.io bundle
I am sorry, I don't know what that means. That files needs to be copied to shinyapps.io, otherwise shinyapps.io will have no access to your password.

**Comment by zahedim** [comment]
Hi,

I'm a junior into the topic encryption; 
I'm using the env var (.Renviron) to store my db credentials. I added the file to .gitignore. Now, I wanna have the pwd encrypted, so I'm using the package 'safer' to encrypt my pwd (https://rdrr.io/cran/safer/man/encrypt_string.html). There is also this method called 'decrypt_string'. I'm asking myself what the purpose of this encryption would be?! Do u have any other recommendations/advices? 

Thx in advance!

**Comment by Oliversinn** [comment]
> Thanks for reponse, @gaborcsardi. I've added an .Renviron file to the project directory. That works great, however how to I avoid committing the file to the bundle?

Can you help me? How can i add this variable in my .Renviron and how can i call it?

**Comment by gaborcsardi** [comment]
See here: https://stackoverflow.com/a/59182727/604364

**Comment by nick-youngblut** [comment]
>The current best practice is to put your password in an env var, set via an .Renviron file in the project directory. The shinyapps.io deployment will pick it up from there automatically. This way at least you don't need to put it in the code. You need to avoid committing the .Renviron file, of course.

One would have to do this for each app. Also, one would have to include all user-specific secrets in each `.Renviron` file (or use just one secret for all users -- a bad idea in many scenarios). 

How does one create a large set of shiny apps on shinyapps.io (or any cloud-based provider) in which each shiny app uses user-specific secrets (e.g., database/API keys)? Any idea why shinyapps.io doesn't implement secrets in the user account settings, similar to GitHub?

**Comment by gaborcsardi** [comment]
@nick-youngblut I am afraid that I can't answer these questions. I was about to suggest asking them at the RStudio community forum, but I can see that you already did that: https://community.rstudio.com/t/database-of-user-api-keys/151836
