### ISSUE TITLE
can't the password back in Linux 

### ISSUE THREAD

**Issue by kasmi** [r-lib/keyring#66]
Hi, I am trying to use the backend function in Linux (no GENOME)
env <- backend_env$new()
env$set("keyring", username ="GLH")
And the following commands will get me password when I try them
env$get("keyring", username ="GLH")
Sys.getenv("keyring:GLH")
However, I am not able to get to password back when needed. I tried to save the "env" as .RData file and read it. the file looks fine but still can get the password. Please let me know how to use this backend function to store password. Thanks

**Comment by gaborcsardi** [comment]
The lifetime of the env var backend is the lifetime of the R session. If you want a persistent key store, consider using the file backend.
