### ISSUE TITLE
Error in namespaceExport(ns, exports) :    undefined exports: askpass, ssh_askpass

### ISSUE THREAD

**Issue by shubharaghav** [r-lib/keyring#70]
Hi, 

I am getting the below error after installing Keyring package and calling the library 
>install.package("Keyring", dependencies = TRUE)
>library("Keyring")
> keyring::key_set(service= "sqldw_pw")
Error in namespaceExport(ns, exports) :    
undefined exports: askpass, ssh_askpass

This may be due this recent change : https://github.com/r-lib/keyring/commit/099006a5360bd490c2a1158f35301add51063f68#diff-9c46cb4f3228981231f7387462e0aeb8

Please suggest how I can resolve this.
Thank You!

**Comment by gaborcsardi** [comment]
I am not sure what you did, but the function is `install.packages()` and the package is called "keyring", with lowercase.

That commit is _not_ in the CRAN version of the package, which you are trying to  use.

**Comment by shubharaghav** [comment]
Sorry for the typos, I just typed some pseudo code in a hurry. 

> packageVersion("keyring")
[1] ‘1.1.0’
