### ISSUE TITLE
Having @ in user name throws an error

### ISSUE THREAD

**Issue by alexhallam** [r-lib/keyring#71]
We switched to using our active directory email and password for sql server login.

If I set `key_set("uid")` as `name@mycompanyname.com` Then try to use it in connecting to a database I get an error

> Cannot open server "mycompanyname.com" requested by the login.  The login failed.

but when I return just `key_get("uid")` 
`name@mycompanyname.com`

 I am guessing the `@` is messing up the parsing somewhere.

The code used to connect to the database is

```r
con <- DBI::dbConnect(odbc::odbc(), Driver = "ODBC Driver 17 for SQL Server", 
Server = "myserver.database.windows.net", 
Database = "mydb", UID = key_get("uid"), PWD = key_get("pwd"))
```

**Comment by gaborcsardi** [comment]
Which backend do you use?

**Comment by alexhallam** [comment]
I am on an Ubuntu Linux so I am guessing `backend_secret_service`.

**Comment by gaborcsardi** [comment]
`@` is not treated specially by keyring AFAICT. That error message is from the database server I think. Maybe it interprets email addresses differently?

In any case, I don't think this is a keyring issue. If you disagree please reopen it. Thanks!
