### ISSUE TITLE
Secret Service API on RStudio Server

### ISSUE THREAD

**Issue by bhogan-mitre** [r-lib/keyring#72]
Is it possible to use the default Linux Secret Service backend from RStudio Server?  It seems at first glance that the X11 requirement may be prohibitive.

```
> kb <- backend_secret_service$new()
> kb$keyring_create(keyring = "foobar") 
Error in b_ss_keyring_create_direct(self, private, keyring, password) :  
  Secret service keyring error in 'create_keyring': 'Error spawning command line “dbus-launch --autolaunch=7cba7f31da5849f4b55980a54d846d50 --binary-syntax --close-stderr”: Child process exited with code 1' 
In addition: Warning message: In b_ss_keyring_create_direct(self, private, keyring, password) :
   Password ignored, will be read interactively 
> system("dbus-launch --autolaunch=7cba7f31da5849f4b55980a54d846d50 --binary-syntax --close-stderr") 
Autolaunch error: X11 initialization failed.
> kb$is_available() 
[1] FALSE
> system("which gnome-keyring-daemon") 
/usr/bin/gnome-keyring-daemon
```

**Comment by bhogan-mitre** [comment]
This issue is potentially related: https://github.com/r-lib/keyring/issues/47

**Comment by gaborcsardi** [comment]
Yes, I am afraid that you cannot do that. In theory you could have a SS client without X11, but I don't know any and I don't know a way to use the regular clients without X11.

**Comment by bhogan-mitre** [comment]
Thanks for the reply.  What do you think about using `secret-tool` to access SS without X11?  That is recommended in the [Gnome Keyring documentation](https://wiki.archlinux.org/index.php/GNOME/Keyring):

> secret-tool — Access the GNOME keyring (and any other service implementing the DBus Secret Service API) from the command line.
https://wiki.gnome.org/Projects/Libsecret || libsecret 

and leveraged by the [`keyringr` package](https://cran.rstudio.com/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html):

``` 
keyringr::decrypt_gk_pw
function (key_value_pairs) 
{
    stopifnot(Sys.info()["sysname"] == "Linux")
    invisible(system(paste("secret-tool lookup ", key_value_pairs, 
        sep = ""), intern = TRUE))
}
```

**Comment by gaborcsardi** [comment]
Well, when the keyring is locked then the above will bring up an X11 dialog. Similarly for storing items:
```
csardi@ubuntu1604:~$ secret-tool store --label='label' attr val

(secret-tool:9235): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
secret-tool: Cannot autolaunch D-Bus without X11 $DISPLAY
csardi@ubuntu1604:~$ secret-tool lookup attr val

(secret-tool:9241): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
secret-tool: Cannot autolaunch D-Bus without X11 $DISPLAY
```
