### ISSUE TITLE
add a keyring_exist method

### ISSUE THREAD

**Issue by cderv** [r-lib/keyring#76]
This is a sugestion to add a `keyring_exists` method. Something like this 
```r
keyring_exist <- function(keyring = NULL) {
  keyring <- keyring %||% private$keyring
  keyring %in% self$keyring_list[["keyring"]]
}
```

This would allow to easily test if a keyring exists in a backend supporting multi keyring. 

I encounter this use case while configuring some environment (RStudio Servers) to use file backend instead of default env backend. File backend seems to be the only one that can't use a default keyring without a `keyring_create` call first. 

``` r
library(keyring)
Sys.setenv(R_KEYRING_BACKEND = "file")
kb <- default_backend()
kb$keyring_list()
#> [1] keyring     num_secrets locked     
#> <0 rows> (or 0-length row.names)
kb$set_with_value(service = "new-serv", "user", "pwd")
#> Error in b_file_keyring_is_locked(self, private, keyring): Keyring `system` does not exist
kb$keyring_create()
kb$keyring_list()
#>   keyring num_secrets locked
#> 1  system           0   TRUE
```

<sup>Created on 2019-08-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Si I would like to test if keyring exists and offer to create a default one otherwise for new user. I do that currently with some code in `Rprofile.site` like this one.
``` r
library(keyring)
Sys.setenv(R_KEYRING_BACKEND = "file")
kb <- default_backend()
if (! kb$.__enclos_env__$private$keyring %in% kb$keyring_list()$keyring) {
    message("To use default, keyring please run", 
            '\n   library("keyring")', 
            '\n   kb <- default_keyring()', 
            '\n   kb$keyring_create()', 
            '\nand enter a personal password for this default keyring') 
}
#> To use default, keyring please run
#>    library("keyring")
#>    kb <- default_keyring()
#>    kb$keyring_create()
#> and enter a personal password for this default keyring
```

<sup>Created on 2019-08-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This creation step is required even for the Rstudio feature [describe in Support](https://support.rstudio.com/hc/en-us/articles/360000969634-Using-Keyring) on a RStudio Server because libsecret does not work if no GUI. 

Would you consider a PR to add a `keyring_exists` method ?

**Comment by gaborcsardi** [comment]
Yes, I would be happy to consider that.

**Comment by gaborcsardi** [comment]
I am closing this now, but feel free to add it if you still want it.

**Comment by cderv** [comment]
I don't use it as much, and do not manage rstudio server anymore, but this one is related to @nwstephens issues with libsecret not being available by default, and the ability to use file backend. Never took the time to make a PR back then.

If I remember correctly the aim of this was to be able to configure RStudio server to use the file backend by default - which would require a user to have it create it in order to use it. 

Would that still be of interest @nwstephens ? or you have other plans in mind ?

**Comment by nwstephens** [comment]
Yes, we are looking for drop dead easy ways to use keyring on a Linux server (presumably with RStudio Server [Pro]). Prompting the user to manually create the "system" keyring -- or any other named keyring -- should be implemented. So I think this function should exist.

But I would go further. It would be nice if `rstudioapi::askForSecret()` could prompt the user to create the system keyring automatically if it doesn't already exist. And per https://github.com/r-lib/keyring/issues/99, it would be worth considering a way to make setting the password easier as well. For example, the first time a user executes `askForSecret()` we might consider the following workflow:

1. > askForSecret("mysql")
2. > "The system keyring does not exist would you like to create it? Y/n"
3. > "Y"
4. > "Please enter a password to lock and unlock the system keyring:"
5. > *********

Then `askForSecret()` would prompt the user to set the "mysql" password in a pop up, and subsequent calls for `askForSecret()` would also use a pop up.

**Comment by gaborcsardi** [comment]
Right. Note, that you don't need a `keyring_exist` method for this. You can already check if a "system" keyring exists, it is only one line of code:
```
"system" %in% self$keyring_list[["keyring"]]
```
