### ISSUE TITLE
keyring_create fails for backend_secret_service

### ISSUE THREAD

**Issue by eyherabh** [r-lib/keyring#83]
The example given in the manual of backend_secret_service was triggering an error with message "Error: attempt to apply non-function" due to calling kb$create_keyring instead of calling kb$keyring_create. Fixing the example by calling the latter does not solve the issue. I fixed it by replacing create_keyring with keyring_create in the manual, on R side, and on C side. Now it works without errors. This is done in pull-request #82

**Comment by nwstephens** [comment]
This is a good catch, thank you for pointing it out. The correct command is `keyring_create()` but the example in `backend_secret_service()` has it as `create_keyring()`. Confusing indeed! I agree that the docs should be fixed.
