### ISSUE TITLE
my windows keyring has disappeared (maybe), what happened to it and what keyring do I have now?

### ISSUE THREAD

**Issue by chrisumphlett** [r-lib/keyring#94]
I'm using keyring on an azure virtual machine, for R scripts that I run as automated processes with Windows Task Scheduler. I've been using keyring reliably for months. All of a sudden, a bunch of scripts failed because my code to pull keys is returning nothing. I had a named keyring with a passcode. It appears to be gone.

When I run `keyring::keyring_list()` I do have something though:
```
  keyring num_secrets locked
1                   9  FALSE
````

What is "1"? I think 9 is the number of secrets I had. But I can't figure out how to access this. I've tried `keyring::key_list(keyring = )` where I used 1, "1" as names.

And what happened to my original keyring? How can I troubleshoot?

When the script runs via a batch file, I get this error:

```
Error in b_wincred_i_get(target) : 
  Windows credential store error in 'get': Element not found.

Calls: source ... b_wincred_parse_keyring_credential -> rawToChar -> b_wincred_i_get
Execution halted
```

I found one [SO post](https://stackoverflow.com/questions/52451952/error-when-using-r-to-get-credentials-from-windows-cred-vault) that pointed me to make sure the credentials exist in Windows Credentials, I think they do ('credentials' is the name of the keyring):
![image](https://user-images.githubusercontent.com/7210482/114193152-3c9d2e00-991c-11eb-8ced-70ad248627d6.png)

**Comment by gaborcsardi** [comment]
The name of the default keyring is the empty string on Windows. You can list your keys with 
```
keyring::key_list()
```

This uses the default keyring.

**Comment by chrisumphlett** [comment]
I forgot that I had tried that as well:
```
> keyring::key_list()
[1] service  username
<0 rows> (or 0-length row.names)
```

**Comment by gaborcsardi** [comment]
How about 
```
keyring::key_list(keyring = "")
```

**Comment by chrisumphlett** [comment]
Same result
```
> keyring::key_list(keyring = "")
[1] service  username
<0 rows> (or 0-length row.names)
```

**Comment by gaborcsardi** [comment]
Well, if you can't see your keys in the Credentials tool, then the keys are indeed gone, I am afraid. Can you see them there?

**Comment by chrisumphlett** [comment]
by "Credentials tool", do you mean the "Credential Manager" in Windows Control Panel? I don't see a way to look at the keys in there. My screenshot was to show that the keyring still seemed to exist (if that's indeed what it was).

**Comment by gaborcsardi** [comment]
What does 

```
keyring::key_list(keyring = "credentials")
```

list? Seems like `credentials` is actually the name of a keyring.

**Comment by chrisumphlett** [comment]
Yes, it is. But it's acting as if it's not there:
```
> keyring::key_list(keyring = "credentials")
[1] service  username
<0 rows> (or 0-length row.names)
```

Here's what I might normally run:
```
> keyring::keyring_unlock(keyring = "credentials", password = "the password")
> user_name <- keyring::key_list(keyring="credentials")[5,2]
[1] NA
> password <- keyring::key_get(service = "service_name", keyring = "credentials", username = user_name )
Error in b_wincred_i_get(target) : 
  Windows credential store error in 'get': Element not found.
```

formerly that unlocked the keyring, and pulled out a user name and password for a particular account.

**Comment by gaborcsardi** [comment]
Right, that indeed means that the keys are not there anymore.

**Comment by chrisumphlett** [comment]
I agree. I was hoping to either a) figure out how to access that "Default" keyring and use it, or, b) have some idea of what happened to make it disappear. Because I need to decide if I think this is reliable in this environment or if I should set up a different process.

**Comment by gaborcsardi** [comment]
It is impossible to tell how they disappeared, unfortunately. All programs on your system can _delete_ a key, they don't have to authenticate for that. That's just how the Windows credential store works.

Depending on what you are storing in the keyring, it might make sense to store it at another secure place as well, e.g. in a password manager or similar. Some credentials are easy to replace, others are not.

**Comment by gaborcsardi** [comment]
It is also possible that you ran into a bug like this: https://superuser.com/questions/1568383/log-deleted-credentials-from-windows-credentials-manager

**Comment by chrisumphlett** [comment]
thankfully the keyring/windows credential store was not the place for storing these. We have a corporate vault. `keyring` was the method I negotiated with our security team as the best balance of ease + security. I had previously been using `.Renviron`. This way kept them encrypted if someone got access to the files on the machine.

I'm looking at some of the stuff in that thread, so far nothing appears to explain.

Would you expect the keyring to be in "Windows credentials" or "generic credentials" in the credentials manager?

**Comment by gaborcsardi** [comment]
Generic credentials.

**Comment by chrisumphlett** [comment]
This article led me to find the log that shows when the problem started: https://www.winhelponline.com/blog/windows-10-forgets-passwords-outlook-edge/

I don't have a scheduled task that runs at that time though, so it doesn't entirely make sense, and there's no log event I could find that shows the deletion happening.

![image](https://user-images.githubusercontent.com/7210482/114234900-63c02380-994d-11eb-9f89-bce2ebd6da58.png)

My windows is not the 2004 build that they say has this bug, it's an earlier build that they explicitly say doesn't have the bug :(

**Comment by chrisumphlett** [comment]
Well, thank you for your help. I think I'll set up another one, but try out the backup feature that your link suggests. If I can successfully delete and restore, then that's a reliable enough plan I think. 

I currently have some things scheduled via RStudio Connect, and I use the environment variables on the server for that. If I could a) run R scripts on RSC directly (I know I could source in via Rmd or put the code into an Rmd, but there's overhead to that I'd rather not deal with right now) and b) there was some kind of keyring/central .Renviron that could be used across all the files on RStudio Connect, then I'd just move a lot of these to there and not have to bother with Task Scheduler/Windows at all. If I'm missing something about how I could do that, someone let me know!

**Comment by jthomasmock** [comment]
> Well, thank you for your help. I think I'll set up another one, but try out the backup feature that your link suggests. If I can successfully delete and restore, then that's a reliable enough plan I think.
> 
> I currently have some things scheduled via RStudio Connect, and I use the environment variables on the server for that. If I could a) run R scripts on RSC directly (I know I could source in via Rmd or put the code into an Rmd, but there's overhead to that I'd rather not deal with right now) and b) there was some kind of keyring/central .Renviron that could be used across all the files on RStudio Connect, then I'd just move a lot of these to there and not have to bother with Task Scheduler/Windows at all. If I'm missing something about how I could do that, someone let me know!

I've logged this as a feature request for RStudio Connect proper. Thanks Chris!
